import { type NextPage } from "next";
import Head from "next/head";

const About: NextPage = () => {
  return (
    <>
      <Head>
        <title>About Mudra Connect</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div>
          <h1>VERSION 1.0.0</h1>
          <br />
          <h3>Created with Love by Dhananjay</h3>
        </div>
      </main>
    </>
  );
};

export default About;
