import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mudra Connect</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>

      <main className="mx-auto max-w-7xl"></main>
    </>
  );
};

export default Home;
